# Generated by Django 4.2.4 on 2023-08-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("seat_num", models.IntegerField()),
                ("days", models.CharField(max_length=30)),
            ],
        ),
    ]
