# Generated by Django 4.2.4 on 2023-09-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_employees_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("array_data", models.TextField()),
            ],
        ),
    ]
