# Generated by Django 4.2.4 on 2023-09-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_grid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatingChartState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_data", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="Grid",
        ),
    ]
