# Generated by Django 4.2.4 on 2023-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_seatingchartstate_delete_grid"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatingchartstate",
            name="cols",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="seatingchartstate",
            name="rows",
            field=models.IntegerField(default=4),
        ),
    ]
