# Generated by Django 4.2.4 on 2023-09-06 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_indexedseating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indexedseating",
            old_name="replicated_array",
            new_name="indexed_array",
        ),
    ]
