# Generated by Django 4.2.4 on 2023-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_indexedseating_day_by_day_seating"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexedseating",
            name="min_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="indexedseating",
            name="min_seats",
            field=models.IntegerField(default=0),
        ),
    ]
