# Generated by Django 4.2.4 on 2023-09-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_indexedseating_day_by_day_seating"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexedseating",
            name="employee_schedule",
            field=models.JSONField(default=dict),
        ),
    ]
